---
- name: Add repository
  hosts: all
  gather_facts: False
  tasks:
   - yum_repository:
       name: "{{ repo_name }}"
       description: "{{ repo_description }}"
       baseurl: "{{ repo_url }}"
       enabled: "yes"
       state: "present"
       gpgcheck: "no"
       repo_gpgcheck: "no"
